name: ci odh-web-components-pagebuilder

on:
  push:
    branches: [ development, master ]
    paths-ignore:
      - "README.md"

  pull_request:
    branches: [ development, master ]
    paths-ignore:
      - "README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # use 18.04 to have old mvn with http support, 20.04 mvn only accepts https repos
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Test with Maven
        run: mvn -B -U clean test verify
